In [15]:
import pandas as pd
import numpy as np
#after importing dependencies we import different classifiers on which we will test our model

In [16]:
from sklearn.linear_model import LogisticRegression
#for regression models

In [17]:
from sklearn.naive_bayes import GaussianNB
#for naive bayes model

In [18]:
from sklearn.neighbors import KNeighborsClassifier
#for K Neighbors model or classifier

In [19]:
from sklearn.tree import DecisionTreeClassifier
#for Decision tree classifier

In [20]:
from sklearn.svm import SVC
#for Support Vector Classifier

In [21]:
from sklearn import metrics
#for confusion matrix used for calculating accuracy of classification models

In [33]:
from sklearn import model_selection

In [34]:
df = pd.read_csv("E:\Work\Iris.csv")

In [11]:
df.head()

Sepal_length  Sepal_width  Petal_length  Petal_width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [12]:
df.describe()

Sepal_length  Sepal_width  Petal_length  Petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [35]:
x = df.iloc[:,[0,1,2,3]]

In [18]:
x.head()

Sepal_length  Sepal_width  Petal_length  Petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [36]:
y = df.iloc[:,[4]]

In [20]:
y.head()

Class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [37]:
x_train , x_test , y_train , y_test = cross_validation.train_test_split(x , y , test_size=0.2)

In [38]:
#Applying Logistic Regression Classifier
clf=LogisticRegression()

In [39]:
clf.fit(x_train, y_train) 


C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [24]:
print(clf)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [39]:
predicted = clf.predict(x_test)

In [40]:
print(metrics.classification_report(y_test, predicted))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.71      1.00      0.83         5
 Iris-virginica       1.00      0.85      0.92        13

    avg / total       0.95      0.93      0.94        30



In [41]:
print(metrics.confusion_matrix(y_test, predicted))

[[12  0  0]
 [ 0  5  0]
 [ 0  2 11]]


In [44]:
print('Accuracy=%f '%(metrics.accuracy_score(y_test, predicted)))

Accuracy=0.933333 


In [45]:
#AND WE ARE DONE WITH LOGISTIC REGRESSION


In [53]:
#NOW USING NAIVE BAYES CLASSIFIER
clf1 = GaussianNB()

In [55]:
clf1.fit(x_train, y_train)

C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [62]:
predicted1 = clf1.predict(x_test)

In [63]:
print(metrics.classification_report(y_test, predicted1))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.83      1.00      0.91         5
 Iris-virginica       1.00      0.92      0.96        13

    avg / total       0.97      0.97      0.97        30



In [64]:
print(metrics.confusion_matrix(y_test, predicted1))

[[12  0  0]
 [ 0  5  0]
 [ 0  1 12]]


In [65]:
print('Accuracy=%f' %(metrics.accuracy_score(y_test, predicted1)))

Accuracy=0.966667


In [40]:
#Now lets move on to K nearest neighbors.
clf2=KNeighborsClassifier()

In [41]:
clf2.fit(x_train, y_train)

C:\Users\Shubham\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [43]:
predicted2 = clf2.predict(x_test)

In [44]:
print(metrics.classification_report(y_test, predicted2))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      0.83      0.91        12
 Iris-virginica       0.85      1.00      0.92        11

    avg / total       0.94      0.93      0.93        30



In [45]:
print(metrics.confusion_matrix(y_test, predicted2))

[[ 7  0  0]
 [ 0 10  2]
 [ 0  0 11]]


In [46]:
print('Accuracy=%f' %(metrics.accuracy_score(y_test, predicted2)))

Accuracy=0.933333


In [47]:
#applying SVM classifier now
clf3=SVC()

In [48]:
clf3.fit(x_train, y_train)

C:\Users\Shubham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
predicted3 = clf3.predict(x_test)

In [50]:
print(metrics.classification_report(y_test, predicted3))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      0.92      0.96        12
 Iris-virginica       0.92      1.00      0.96        11

    avg / total       0.97      0.97      0.97        30



In [51]:
print(metrics.confusion_matrix(y_test, predicted3))

[[ 7  0  0]
 [ 0 11  1]
 [ 0  0 11]]


In [52]:
print('Accuracy=%f' %(metrics.accuracy_score(y_test, predicted3)))

Accuracy=0.966667


In [54]:
#Now using Decision Tree Classifier
clf4=DecisionTreeClassifier()

In [55]:
clf4.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [56]:
predicted4=clf4.predict(x_test)

In [57]:
print(metrics.classification_report(y_test, predicted4))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.92      0.92      0.92        12
 Iris-virginica       0.91      0.91      0.91        11

    avg / total       0.93      0.93      0.93        30



In [58]:
print(metrics.confusion_matrix(y_test, predicted4))

[[ 7  0  0]
 [ 0 11  1]
 [ 0  1 10]]


In [59]:
print('Accuracy_Score=%f' %(metrics.accuracy_score(y_test, predicted4)))

Accuracy_Score=0.933333


In [ ]:
# AND.WE.ARE.DONE